spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee-shop-product
    username: postgres
    password: password
  sql:
    init:
      mode: always
