server:
  port: 0
spring:
  application:
    name: product-service
    instance_id: ${random.uuid}
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/coffee-shop-product}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
  sql:
    init:
      mode: always
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
