server:
  port: 0
spring:
  application:
    name: cart-service
    instance_id: ${random.uuid}
  data:
    mongodb:
      uri: ${DATABASE_URI:mongodb://admin:password@127.0.0.1:27017/cartservice?authSource=admin}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
